services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}survey-api
    build:
      context: .
      dockerfile: Survey.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080:80
      - ASPNETCORE_HTTPS_PORTS=8081:443
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
     - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
volumes:
  postgres_volume:
  pgadmin_volume:  

